* om-svg-tut
Sudoku using om react svg core.async core.match

** Overview
A simple sudoku gui for playing in a browser, in color, with animations.

** Setup
Compile clojurescript to javascript by,
#+BEGIN_SRC shell
lein cljsbuild auto dev
#+END_SRC
and then open index.html in a broswer.

To use a browser repl,
uncomment
#+BEGIN_SRC clojure
(repl/connect "http://localhost:9000/repl")
#+END_SRC
in core.cljs
and then run
#+BEGIN_SRC shell
./scripts/erepl
#+END_SRC
and reload index.html.

** Resources
*** SVG
    http://www.w3.org/TR/SVG/Overview.html
    https://developer.mozilla.org/en-US/docs/Web/SVG

**** Fonts in svg
     http://nimbupani.com/about-fonts-in-svg.html
*** Sudoku
    Backtracking
    http://en.wikipedia.org/wiki/Backtracking

    Sudoku solving algorithms
    http://en.wikipedia.org/wiki/Sudoku_solving_algorithms

    Sudoku as aConstraint Problem
    http://4c.ucc.ie/~hsimonis/sudoku.pdf

    Sudoku Explainer
    http://diuf.unifr.ch/pai/people/juillera/Sudoku/Sudoku.html

    Some interesting Sudokus
    http://diuf.unifr.ch/pai/people/juillera/Sudoku/InterestingSudokus.html

    A Pencil-and-Paper
    Algorithm for Solving
    Sudoku Puzzles
    J.F.Crook
    http://www.ams.org/notices/200904/rtx090400460p.pdf

    Solving Every Sudoku Puzzle
    Peter Norvig
    constraint propegation and search
    http://norvig.com/sudoku.html

    clojure version:
    https://jkkramer.wordpress.com/2011/03/29/clojure-python-side-by-side/

*** core.logic
    https://github.com/clojure/core.logic

    to solve sudoku
    https://gist.github.com/swannodette/3217582

    Constraint Logic Programming
    http://en.wikipedia.org/wiki/Constraint_logic_programming

    Edmund Jackson
    core.logic.intro
    Euro clojure 2012
    https://vimeo.com/45128721

** License
Copyright © 2014 Walter Patrick Babic

Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
